[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
ithaca_smart_contract_sol = "453oGKKhp9Ai64DJjdgUR7YxJA2uAn5edyaEfopZ7EQ7"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "7u3HeHxYDLhnCoErrtycNokbQYbWGzLs6JSDqGAv5PfF" # kamino_lend_main_market

[[test.validator.clone]]
address = "9DrvZvyWh1HuAoZxvYWMvkf2XCzryCpGgHqrMjyDWpmo" # kamino_reserve_1

[[test.validator.clone]]
address = "2UywZrUdyqs5vDchy7fKQJKau2RVyuzBev2XKGPDSiX1" # kamino_sol_col_token

[[test.validator.clone]]
address = "GafNuUXj9rxGLn4y79dPu6MHSuPWeJR6UtTWuexpGh3U" # kamino_reserve_liq_sol

[[test.validator.clone]]
address = "d4A2prbA2whesmvHaL88BH6Ewn5N4bTSU2Ze8P6Bc4Q" # kamino_reserve_sol_state

 [[test.validator.clone]]
 address = "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD" # kamino_lend_program

[[test.validator.clone]]
address = "3NJYftD5sjVfxSnUdZ1wVML8f3aC6mp1CXCL6L7TnU8C" # kamino_scope_acc

[[test.validator.clone]]
address = "HFn8GnPADiny6XqUoWE8uRPPxb29ikn4yTuPa9MF2fWJ" # kamino_scope_program

[[test.validator.clone]]
address = "Chpu5ZgfWX5ZzVpUx9Xvv4WPM75Xd7zPJNDPsFnCpLpk" # oracle mappings

[[test.validator.clone]]
address = "rec5EKMGg6MxZYaMdyBfgwp4d5rB9T1VQH5pJv5LtFJ" # pyth sol receiver


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
