[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
ithaca_smart_contract_sol = "453oGKKhp9Ai64DJjdgUR7YxJA2uAn5edyaEfopZ7EQ7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
